#!/bin/bash
# $Id: ipaddr,v 1.3 2007/03/16 15:04:30 gwiley Exp gwiley $
# Glen Wiley <glen.wiley@gmail.com>
#
# perform ip address calculations
#
# TODO add syntax checking for ip addresses

#---------------------------------------- usage
function usage
{
	echo "USAGE: ipaddr -a <ip1> <ip2>..."
	echo "-a   convert each ip to an integer (as inet_aton())"
	echo "-n   convert each integer to an ip (as inet_ntoa())"
} # usage

#---------------------------------------- inet_aton
# convert dotted notation ip address to an integer
# pass in a dotted notation ip address to convert
function inet_aton
{
	ipq=( ${1//\./ } )
	echo $(echo "(${ipq[0]} * ( 2 ^ 24 )) + (${ipq[1]} * ( 2 ^ 16 )) + (${ipq[2]} * ( 2 ^ 8 )) + (${ipq[3]}  * (2 ^ 0))" | bc)
} # inet_aton

#---------------------------------------- inet_ntoa
# convert an integer ip address to dotted notation
# pass in a single argument which in the integer to convert
function inet_ntoa
{
	bc <<-EOF
		a=$1/(2 ^ 24)
		b=($1 - (a * (2 ^ 24)))/(2 ^ 16)
		c=($1 - ((b * (2 ^ 16)) + (a * (2 ^ 24))))/(2 ^ 8)
		d=($1 - ((c * (2 ^ 8)) + (b * (2 ^16)) + (a * (2 ^ 24))))
		print a,".",b,".",c,".",d
	EOF
} # inet_ntoa

#---------------------------------------- main
mode="aton"

while getopts "?na" opt
do
	case "$opt" in
		a) mode="aton";;
		n) mode="ntoa";;
		?) usage; exit 1;
	esac
done

OPTIND=$(( OPTIND - 1 ))
shift $OPTIND
for ip in $@
do
	t=${ip#[0-9]*.}
	if [ ${#t} -ne ${#ip} ]
	then
		echo -n "$ip "
		inet_aton $ip
	else
		inet_ntoa $ip		
		echo " $ip"
	fi
done

# ipaddr
